# Clean and wrangle data

## Setup

```{r}
library(dplyr)
library(tidyr)
library(readr)
```

## Source data

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

## Clean and reshape data

```{r}
colnames(catch_original)
head(catch_original)
summary(catch_original)
glimpse(catch_original)
```

## Clean and reshape data again

```{r}
catch_data <- catch_original %>% 
    select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
```


```{r}
catch_clean <- catch_data %>% 
    mutate(
        Chinook = if_else(
            Chinook == "I",
            "1",
            Chinook),
    Chinook = as.numeric(Chinook))
```


### Go

```{r}
catch_long <- catch_clean %>% 
    pivot_longer(cols = -c(Region, Year),
    names_to = "species",
    values_to = "catch_thousands")

```

```{r}
catch_wide <- catch_long %>%
    # Pivot the data back into wide format
    tidyr::pivot_wider(names_from = species,
        values_from = catch_thousands,
        values_fill = 0)

# Check the result
head(catch_wide)
```


## Not sure where I am anymore
```{r}
catch_long <- catch_long %>% 
    mutate(catch = catch_thousands * 1000) %>% 
    select(-catch_thousands)
head(catch_long)
```

```{r}
mean_region <- catch_long %>% 
    group_by(Region) %>% 
    summarize(mean_catch = mean(catch, na.rm = TRUE), .groups = "drop") %>% 
    arrange(desc(mean_catch))

head(mean_region)
```


```{r}
sse_catch <- catch_long %>% 
    filter(Region == "COP")

head(sse_catch)
```


```{r}
sites_df <- data.frame(site = c("HAW-101", "HAW-103", "OAH-320", "OAH-219", "MAU-039"))
sites_df %>% 
    separate_wider_delim(cols=site, delim= "-",
    names = c("island", "site_number"),
    cols_remove = FALSE)

```


```{r}
dates_df <- data.frame(
    year  = rep(x = "1930", times = 3),
    month = rep(x = "12",   times = 3),
    day   = 14:16)

# Check that
dates_df %>% 
    unite(
        col = date,
        year, month, day,
        sep = "-",
        remove = FALSE
    )
```
